/* DO NOT EDIT THIS FILE - it is machine generated */
#include "platform_asset_utils.h"
#include "macros.h"
#include "platform_log.h"
#include <android/asset_manager_jni.h>
#include <assert.h>

#define TAG "asset_util"

AAssetManager* asset_manager = NULL;

void release_asset_data(FileData* file_data) {
	assert(file_data != NULL);
	assert(file_data->data != NULL);

    free(file_data->data);
    file_data->data = NULL;
}

FileData get_asset_data(const char* filename)
{
	assert(asset_manager);

	void* data = NULL;
	size_t data_size = 0;

    AAsset* file = AAssetManager_open(asset_manager, filename, AASSET_MODE_STREAMING);
    if(file) {
        off_t file_size = AAsset_getLength(file);
        data = malloc(file_size);
        data_size = file_size;

        DEBUG_LOG_PRINT_D(TAG, "Successfully loaded file %s (length=%d)", filename, data_size);

        AAsset_read(file, data, file_size);
        AAsset_close(file);
        file = NULL;
    }
    else
    {
    	DEBUG_LOG_PRINT_D(TAG, "Failed to load file %s", filename);
    }

    return (FileData) {data_size, data};
}

/*
 * Class:     com_example_jilgameengine_GameLibJNIWrapper
 * Method:    init_asset_manager
 * Signature: (Landroid/content/res/AssetManager;)V
 */

JNIEXPORT void JNICALL Java_com_example_jligameengine_GameLibJNIWrapper_initAssetManager(
	    JNIEnv * env, jclass jclazz, jobject java_asset_manager) {
	    UNUSED(jclazz);
	    asset_manager = AAssetManager_fromJava(env, java_asset_manager);
	}
